version: "3.8"

services:
  frontend:
    image: praveen007bot/task-frontend:latest
    ports:
      - "80:80"  # Expose port 3000 on the host to port 80 in the container
    depends_on:
      - backend  # Ensure backend starts before frontend
    networks:
      - app-network

  backend:
    image: praveen007bot/task-backend:latest
    ports:
      - "8000:8000"  # Expose port 8000 on the host to port 8000 in the container
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
